### ISSUE TITLE
android的配置可能不正确

### ISSUE THREAD

**Issue by openproject** [tuna/mirror-web#1]
在https://wiki.tuna.tsinghua.edu.cn/MirrorUsage/android 这个上面，按照上面说明操作，是走不通的。
因为https://android.tuna.tisnghua.edu.cn/ 访问不了，导致配置android源的时候无法使用。

ps:作为国内首个提供android mirror的开源镜像中心，是非常有意义的，望修复配置问题，造福围墙内的守望者们！

**Comment by huiyiqun** [comment]
挖个坟，是否可能是网络问题？

**Comment by alick9188** [comment]
@openproject 有没测试结果？是否正常可用？

**Comment by cimoing** [comment]
没法使用并发，只有-j1时不会报错，多加一个并发都不行
