### ISSUE TITLE
How to make a site like `mirrors.tuna.tsinghua.edu.cn`

### ISSUE THREAD

**Issue by liudonghua123** [tuna/mirror-web#105]
I know this repo is the front end of the `mirrors.tuna.tsinghua.edu.cn` site. I want to make a mirror site like this wonderful one, I also looked https://github.com/tuna/tunasync-scripts/https://github.com/tuna/tunasync, but still could not find any documentation on how to build the backend of the site, could you give me some tips or instructions.

Thanks in advance!

**Comment by shankerwangmiao** [comment]
Hi,

本 Repo 是镜像站前端网页，是纯静态的。它与后端通信的接口有 3 个，是 JSON 文件。分别是 `/static/tunasync.json` 用于获取同步状态；`/static/tunet.json` 用于判断用户是否在清华校内；`/static/status/isoinfo.json` 用于获取 ISO 镜像的信息，供“获取下载链接”按钮使用。

其中，`isoinfo.json` 是静态文件，由 
https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.py 定时生成；`tunet.json` 是直接由 nginx 判断返回 `true` 或者 `false`，目前由于基础设施升级，该功能不需要了，因此一律返回 `false`。`tunasync.json` 由 nginx 转发到 tunasync manager 处理，转发到 tunasync manager 的 `/jobs` 接口，相关代码在 https://github.com/tuna/tunasync/blob/ef78563b8cef311ca57f4f0b02b40764dc4b091d/manager/server.go#L75 和 https://github.com/tuna/tunasync/blob/ef78563b8cef311ca57f4f0b02b40764dc4b091d/manager/server.go#L130

**Comment by liudonghua123** [comment]
@shankerwangmiao Thank you very much!
