### ISSUE TITLE
如何生成disk.json 以及流量图 CPU Memory图

### ISSUE THREAD

**Issue by Driverorz** [tuna/mirror-web#123]
你好！如题，请问下disk.json文件在后端如何生成的？https://mirrors.tuna.tsinghua.edu.cn/static/status/disk.json
以及  实时流量图 服务器资源占用图是怎样生成的？谢谢。
https://mirrors.tuna.tsinghua.edu.cn/status/#syncing-status

**Comment by Driverorz** [comment]
disk硬盘使用情况估计是反代理php来获取的吗？服务器状态图那个实在是猜不出来是怎样做的。

**Comment by GaryH4** [comment]
grafana

**Comment by Harry-Chen** [comment]
disk.json 通过我们自己的脚本输出
其他的图是 Grafana 绘制的
