### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by dingchengshan** [tuna/mirror-web#131]
请问能否增加预装软件版本标注，如使用centos系统需要提前预装哪些软件以及对应的版本？

**Comment by xavieryao** [comment]
感谢你的建议。哪些镜像需要这样的标注呢？可以举一些例子吗

________________________________
发件人: Ding Chengshan <notifications@github.com>
发送时间: Friday, May 31, 2019 11:09:11 AM
收件人: tuna/mirror-web
抄送: Subscribed
主题: [tuna/mirror-web] Environment (#131)


请问能否增加预装软件版本标注，如使用centos系统需要提前预装哪些软件以及对应的版本？

―
