### ISSUE TITLE
Hackage和Stackage的帮助说明和stack 2.1.1不兼容

### ISSUE THREAD

**Issue by bjin** [tuna/mirror-web#132]
前两天`stack 2.1.1`发布了，配置文件有了很大的变动，导致之前在`stack 1.x`上`~/.stack/config.yaml`的Hackage和Stackage的tuna镜像设置部分失效了。

具体来说：
1. Sackage的设置， `urls`只剩下`latest-snapshot`有效了。不太确定其他两项是不是还能再使用镜像服务器。
```
Unrecognized fields in urls: lts-build-plans, nightly-build-plans
```
2. Hackage的设置，`name`和`http`都被忽略了，而`download-prefix`则需要变更为`http://mirrors.tuna.tsinghua.edu.cn/hackage/`的样子。
3. Hackage的`package-indices`设置，要求添加haskell-security的声明了，具体参见[stack文档里的例子](https://docs.haskellstack.org/en/stable/yaml_configuration/#package-indices)。
4. 第一次获取package indices如果直接用tuna镜像的话，会碰到如下错误
```
Downloading root
Could not deserialize <repo>/root.json: Malformed: (line 1, column 1):
unexpected "<"
expecting white space or JSON value
```
猜测是hackage security的[api要求](https://hackage.haskell.org/api#security)。不太确定是不是直接同步几个json文件就解决问题了。

**Comment by eccstartup** [comment]
能尝试修复一下吗？
help文档and/or同步脚本

**Comment by jiegec** [comment]
Pull requests are welcome.

**Comment by bjin** [comment]
> 能尝试修复一下吗？
> help文档and/or同步脚本

具体得找时间研究以下Hackage Security的实现机制再看下作哪些更改合适。发这个issue也是想看看有没有其他熟悉这块的同学，能直接给出正解。

**Comment by huandzh** [comment]
@eccstartup 推了两个尚未测试效果的PR。不知哪位同学的环境方便，请帮忙测试一下，thx

**Comment by eccstartup** [comment]
尝试一下吧~
顺便看看这两个脚本是不是也变了
https://github.com/tuna/tunasync-scripts/blob/master/hackage.sh
https://github.com/tuna/tunasync-scripts/blob/master/stackage.py

**Comment by bjin** [comment]
试了下，hackage镜像已经可以用了。

**Comment by cmal** [comment]
同样的问题，请问之前是怎么解决的？ @bjin
