### ISSUE TITLE
Debian Testing 文档需要更新

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/mirror-web#137]
`a...@7...xyz` 报告称，

> 在最新的更新中 (https://wiki.debian.org/Status/Testing) , Debian testing 的 sources.list 文件發生了一點變化 .
> 
> 
> 在貴站的幫助頁面 , testing 源自動生成文件需要修改為新格式才不會報錯 .
> 
> https://mirrors.tuna.tsinghua.edu.cn/help/debian/
> 
> 
> 望盡快修改 .

**Comment by z4yx** [comment]
没懂要怎么改

**Comment by shankerwangmiao** [comment]
应该是 `testing/updates` 改成了 `testing-security`，你可以试一下。
