### ISSUE TITLE
mageia的tuna镜像源

### ISSUE THREAD

**Issue by wuhao1938** [tuna/mirror-web#14]
mageia的tuna镜像源已经提交到http://mirrors.mageia.org/

也可以手动修改/etc/urpmi/urpmi.cfg,更新一下即可,运行

urpmi.update命令

**Comment by bigeagle** [comment]
…… 说得好明白

**Comment by dotkrnl** [comment]
默默地把 https 加进去了。
话说 @wuhao1938 写个清晰点的版本吧毕竟这里没有 Mageia 用户 _(:3」∠)_
