### ISSUE TITLE
IE浏览器支持

### ISSUE THREAD

**Issue by githubitnow** [tuna/mirror-web#145]
当前版本Web前段界面不支持IE浏览器，打开页面后镜像列表内容看不到。似乎是vue兼容性问题？

能否麻烦各位帮忙修正一下，让其能良好支持IE，类似中科大的那个镜像一样

建议IE8及其后续版本都能支持，毕竟国内（特别是一些事业单位）用IE的用户还是挺多的

非常感谢！

**Comment by jiegec** [comment]
有点麻烦，Vue确实不支持IE8。。

**Comment by githubitnow** [comment]
IE11打开也不能正常显示，镜像列表的整个div都看不到
IE8打开页面上会出现一些非正常内容的标签
EDGE浏览器下正常(其他用户反映的，我自己未测试)

我看到很多关于ES6兼容性问题的文章，也尝试了把index.es6转换为.es5，但没有成功
关于vue的IE兼容性问题，应该是个毕竟普遍的现象，希望有空帮忙处理下

谢谢！

**Comment by xavieryao** [comment]
IE8 还没解决

**Comment by shankerwangmiao** [comment]
目前兼容到 IE 7，同时增加了对诸如 lynx 和 w3m 这类终端浏览器的支持。

![image](https://user-images.githubusercontent.com/6825907/63485444-71bbea80-c471-11e9-9c6c-4848f795e62d.png)
![image](https://user-images.githubusercontent.com/6825907/63485483-8b5d3200-c471-11e9-8930-eb19bfeebaeb.png)

**Comment by githubitnow** [comment]
非常感谢！

动作真快！
