### ISSUE TITLE
jekyll build 报错

### ISSUE THREAD

**Issue by ZJKai** [tuna/mirror-web#147]
[root@d32291cb1436 data]# jekyll build           
Configuration file: /data/_config.yml
            Source: /data
       Destination: /data/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Babel encountered an error while converting 'static/js/help.es6':
                    "\xEF" on US-ASCII
jekyll 3.8.5 | Error:  "\xEF" on US-ASCII

**Comment by shankerwangmiao** [comment]
请设置 `LANG` 环境变量为 `en_US.UTF-8`
