### ISSUE TITLE
镜像资源文件浏览页面布局问题

### ISSUE THREAD

**Issue by githubitnow** [tuna/mirror-web#148]
首先感谢各位提供mirror-web这么好的管理页面资源！
还有个问题要请教，我自己架设的mirror-web，在镜像资源文件浏览页面，看到的是类似这样的内容：
-------------------------------------------
Index of /centos/
Name			Last modified
Parent Directory	2019/08/22 15:52	-
2.1/				2009/09/09 13:18	-
2/				2009/09/09 13:18	-
3.1/				2011/03/03 07:44	-
3.3/				2011/03/03 07:44	-
-------------------------------------------
页面过于简陋，没有任何修饰，而且一些长一点的文件名也显示不完整

请问如何做到类似:
https://mirrors.tuna.tsinghua.edu.cn/ubuntu-releases/16.04/
那样的效果，每个资源浏览页面，均基于相同的模板和布局，且对页面内容进行一定的字体及颜色的修饰？

再次感谢！

**Comment by xavieryao** [comment]
nginx 的话可以看看 fancy index

________________________________
发件人: githubitnow <notifications@github.com>
发送时间: Friday, August 23, 2019 5:47:46 PM
收件人: tuna/mirror-web <mirror-web@noreply.github.com>
抄送: Subscribed <subscribed@noreply.github.com>
主题: [tuna/mirror-web] 镜像资源文件浏览页面布局问题 (#148)

首先感谢各位提供mirror-web这么好的管理页面资源！
还有个问题要请教，我自己架设的mirror-web，在镜像资源文件浏览页面，看到的是类似这样的内容：
Index of /centos/
Name Last modified
Parent Directory 2019/08/22 15:52 -
2.1/ 2009/09/09 13:18 -
2/ 2009/09/09 13:18 -
3.1/ 2011/03/03 07:44 -
3.3/ 2011/03/03 07:44 -

页面过于简陋，没有任何修饰，而且一些长一点的文件名也显示不完整

请问如何做到类似:
https://mirrors.tuna.tsinghua.edu.cn/ubuntu-releases/16.04/
那样的效果，每个资源浏览页面，均基于相同的模板和布局，且对页面内容进行一定的字体及颜色的修饰？

再次感谢！

―

**Comment by githubitnow** [comment]
没有用nginx，我的环境如下：
centos 7.2
[mirrors@mirrors _layouts]$ ruby -v
ruby 2.3.2p217 (2016-11-15 revision 56796) [x86_64-linux]
[mirrors@mirrors _layouts]$ node -v
v7.10.1
[mirrors@mirrors _layouts]$ gem -v
3.0.4

**Comment by shankerwangmiao** [comment]
这个需要配合 nginx 的 fancy-index 模块才能实现。Jekyll 渲染出来的页面文件中有 /fancy-index/ 目录，其中有 before.html 和 after.html，就是用来配合 fancy-index 作为索引页面的模板的。

**Comment by githubitnow** [comment]
谢谢!
我再研究研究
