### ISSUE TITLE
是不是不支持IE的？

### ISSUE THREAD

**Issue by dxjia** [tuna/mirror-web#15]
<http://mirrors.tuna.tsinghua.edu.cn/> 好像用IE访问有问题啊，是不是不会去支持了呢？
就问下。。。

**Comment by bigeagle** [comment]
有截图之类的么？主要是没法测试。
理论上应该 IE9+ 都支持的

**Comment by bigeagle** [comment]
我把 jquery 降级到 1.x 了，现在应该可以

**Comment by dxjia** [comment]
抱歉这么晚回复，我电脑上的IE还是IE8，我是把链接发给我一个朋友，他用360，页面直接不显示的，我开始以为我链接给错了，后来chrome里试了下很OK~
用IE8访问，就是 `镜像列表`  区域不显示。。。
