### ISSUE TITLE
Gentoo portage使用帮助改进

### ISSUE THREAD

**Issue by cdluminate** [tuna/mirror-web#158]
https://mirrors.tuna.tsinghua.edu.cn/help/gentoo-portage/

stage3 和 stage4 里没有 `eix-sync` ，而 `emerge --sync` 走 rsync 又超级慢。建议补充推荐使用 `emerge-webrsync` ，以免新手（比如我）掉坑。

**Comment by phy25** [comment]
可对此页面提出 PR：https://github.com/tuna/mirror-web/blob/master/_posts/help/2017-12-29-gentoo-portage.md

**Comment by KireinaHoro** [comment]
Gentoo Handbook 中有[明確指出](https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Base#Installing_an_ebuild_repository_snapshot_from_the_web)推薦第一次同步使用 `emerge-webrsync` 方式進行，以節約帶寬：

> The use of emerge-webrsync is recommended for those who are behind restrictive firewalls (because it uses HTTP/FTP protocols for downloading the snapshot) and saves network bandwidth. Readers who have no network or bandwidth restrictions can happily skip down to the next section.

Handbook 此處給出的建議十分明確且獨立於 Mirror Selection 部分。

至於 `eix-sync` 則完全無關：其僅爲 `eix` 套件爲便於在 sync 後執行 database update 的捷徑。
