### ISSUE TITLE
CentOS8帮助文档

### ISSUE THREAD

**Issue by haozi-dev** [tuna/mirror-web#159]
CentOS8出来有一段时间了，帮助文档一直没跟上更新，不懂设置。

**Comment by phy25** [comment]
https://github.com/tuna/mirror-web/blob/master/_posts/help/1970-01-01-centos.md

**Comment by z4yx** [comment]
可以先参考 https://mirrors.ustc.edu.cn/help/centos.html
把 mirrors.ustc.edu.cn 替换为 mirror.tuna.tsinghua.edu.cn 即可
