### ISSUE TITLE
镜像列表的json更新后路由是如何增加的

### ISSUE THREAD

**Issue by shitou1992** [tuna/mirror-web#161]
更新json后首页镜像列表有内容了，但是点击后提示 ‘/elvish/’ not found，
这个后台是如何实现的需要和nginx结合吗

**Comment by phy25** [comment]
无法复现此问题：https://mirrors.tuna.tsinghua.edu.cn/elvish/

有可能是刚刚同步成功的？

**Comment by shankerwangmiao** [comment]
@shitou1992 对的，mirror-web 仅为前端，它对接 tunasync 的后端显示镜像列表。点开某一镜像后具体镜像文件的服务是 nginx 的配置。

**Comment by shitou1992** [comment]
好的，感谢解惑，我再研究研究
