### ISSUE TITLE
zeitwerk-2.2.2 requires ruby version >= 2.4.4, which is incompatible with the current version, ruby 2.3.8p459

### ISSUE THREAD

**Issue by canghaiwuhen** [tuna/mirror-web#162]
ubuntu 18.04下 docker build失败

**Comment by shankerwangmiao** [comment]
您可以使用预制好的镜像。

https://hub.docker.com/r/tunathu/mirror-web/dockerfile

**Comment by canghaiwuhen** [comment]
@shankerwangmiao 镜像怎么用？没有说明啊

**Comment by shankerwangmiao** [comment]
https://github.com/tuna/mirror-web#build-in-docker
