### ISSUE TITLE
需要补充msys2和cygwin的Help

### ISSUE THREAD

**Issue by scateu** [tuna/mirror-web#17]
Msys2的Help可以参考 <https://lug.ustc.edu.cn/wiki/mirrors/help/msys2>

**Comment by bigeagle** [comment]
康哥你最有经验了…… 其他人都没windows啊

**Comment by scateu** [comment]
我当你是在表扬我喽......

**Comment by bigeagle** [comment]
@scateu 已经 assign 给你了，看着办～

**Comment by scateu** [comment]
https://github.com/tuna/mirror-web/commit/9e070a52bdb9ae3cc555a3905d1d0277886da8e1

但是没有生效？还需要我做啥？

**Comment by bigeagle** [comment]
(是不是还有 cygwin?

**Comment by scateu** [comment]
@scateu 叫你手贱！叫你手贱！叫你手贱！叫你手贱！

**Comment by scateu** [comment]
Done.
