### ISSUE TITLE
Really?

### ISSUE THREAD

**Issue by sysdl132** [tuna/mirror-web#177]
![image](https://user-images.githubusercontent.com/54708046/78451229-e9642000-76b6-11ea-8ae7-2c2318285732.png)
![image](https://user-images.githubusercontent.com/54708046/78451236-fa149600-76b6-11ea-9aad-2e92a54419c2.png)
deb https://mirrors.tuna.tsinghua.edu.cn/ros/ ~~ubuntu~~ **debian** / stretch main

**Comment by z4yx** [comment]
官方确实把两个系统的包都放到了 `ubuntu` 下面，我也很无奈呀

**Comment by sysdl132** [comment]
=====do not comment under this line=====
