### ISSUE TITLE
VLC Windows 版本未出现在镜像站下载链接列表中

### ISSUE THREAD

**Issue by laozhoubuluo** [tuna/mirror-web#227]
#### 发生了什么（What happened）

根据 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.ini 配置文件, VLC Windows 版本应出现在镜像站下载链接列表中 ( 镜像站首页 - 下载链接 - 应用软件 - VLC ), 但实际上 VLC Windows 版本未出现在镜像站下载链接列表中.

#### 期望的现象（What you expected to happen）

VLC Windows 版本应出现在镜像站下载链接列表中.

#### 如何重现（How to reproduce it）

访问镜像站首页, 打开下载链接 - 应用软件 - VLC, 发现VLC Windows版本并未出现在镜像站下载链接列表中.

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows 10 20H1
- 浏览器（如果适用）（Browser version, if applicable）：Firefox 81.0.2 ( 64 Bit )
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
因为 https://mirrors.tuna.tsinghua.edu.cn/videolan-ftp/vlc/3.0.11.1/ 下面只有 mac 版本。这个 issue 怕是解决起来比较麻烦。。。。

**Comment by laozhoubuluo** [comment]
> 
> 
> 因为 https://mirrors.tuna.tsinghua.edu.cn/videolan-ftp/vlc/3.0.11.1/ 下面只有 mac 版本。这个 issue 怕是解决起来比较麻烦。。。。

我是在 https://mirrors.tuna.tsinghua.edu.cn/videolan-ftp/vlc/last/ 找到 Windows 版本的, 本来以为改下正则的问题.
但是后来看了下, last 目录对应的版本居然指向了 3.0.11, 这可就确实不好平衡了......

**Comment by ZenithalHourlyRate** [comment]
参照 <https://www.videolan.org/news.html#news-2020-07-29> 以及之前的发布历史，感觉 3.0.11.1 只是临时的问题，在以后的发布中应该是 macos 与 win 发布在一个文件夹中。

单独写两套匹配规则感觉可行，只需要
```
pattern = vlc/([\d\.]+)/(\w+)/.+\d\.(dmg|exe|msi|7z)(?!.)
```
变成
```
pattern = vlc/([\d\.]+)/(win32|win64)/.+\d\.(dmg|exe|msi|7z)(?!.)
pattern = vlc/([\d\.]+)/macosx/.+\d\.(dmg|exe|msi|7z)(?!.)
```
即可

**Comment by z4yx** [comment]
Fixed
