### ISSUE TITLE
希望可以在lineage页面提供选择版本的功能

### ISSUE THREAD

**Issue by Nappp** [tuna/mirror-web#240]
LineageOS有[众多分支](https://github.com/LineageOS/android/branches)，而[tuna介绍页面](https://mirrors.tuna.tsinghua.edu.cn/help/lineageOS/)却固定成了`cm-14.1`。希望可以参考[Ubuntu介绍页面](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/)提供一个可选的选项，实现上只要将git repo的`branchs`列出来即可
理由有：
- `CM`已经是过去式，现在已经改名叫`Lineage`
- `cm-14.1`对应的是`Android 7.0`，已经是2016年的系统
- 容易误导初学者，我本人就有因为不知道参数的含义而clone错仓库的经历

![image](https://user-images.githubusercontent.com/5286980/105279100-d12ba600-5be1-11eb-9cb8-f34b378ee501.png)
![image](https://user-images.githubusercontent.com/5286980/105279128-de489500-5be1-11eb-9d10-3a32bf9bcb53.png)

**Comment by Harry-Chen** [comment]
欢迎提供 PR

**Comment by xavieryao** [comment]
感觉直接把 `-b xxx` 就行了

**Comment by Nappp** [comment]
好的，那近期会尝试抽空修改
