### ISSUE TITLE
帮助文档页面展示bug

### ISSUE THREAD

**Issue by JacianLiu** [tuna/mirror-web#265]
#### 发生了什么（What happened）

帮助文档页面footer标签跑到了顶部，挡住了文档内容，并且上下移动页面不会恢复

#### 期望的现象（What you expected to happen）

页面正常显示

#### 如何重现（How to reproduce it）

页面上鼠标左键连续点击三下

#### 其他事项（Anything else we need to know）
- 该问题是否被之前的 issue 提出过：无

#### 您的环境（Environment）
- 操作系统（OS Version）：Windows10 企业版 19042.508
- 浏览器（如果适用）（Browser version, if applicable）：Chrome
- 其他（Others）：

**Comment by shankerwangmiao** [comment]
ref: #214
