### ISSUE TITLE
Homebrew-bottles 镜像使用 帮助似乎需要更新

### ISSUE THREAD

**Issue by yichengsu** [tuna/mirror-web#272]
#### 发生了什么（What happened）
Homebrew-bottles 镜像使用帮助中的链接似乎应该以`homebrew-bottles/bottles`结尾

#### 如何重现（How to reproduce it）and 期望的现象（What you expected to happen）
目前的使用帮助在 MAC 11.2.3 无法安装，修改后即可

**Comment by ZenithalHourlyRate** [comment]
参考 https://github.com/tuna/issues/issues/1224#issuecomment-917467113

> 目前，该环境变量的两种形式均可使用，即
> 
> export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles"
> export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles"
> 
> 另注：
> 
> export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/linuxbrew-bottles/bottles/bottles/bottles"
> 也能正常使用。

homebrew-bottles 同理。
