### ISSUE TITLE
可否分享nginx中首页的配置？

### ISSUE THREAD

**Issue by nightcoffee** [tuna/mirror-web#276]
在 https://github.com/tuna/mirror-web/issues/233#issuecomment-745750414 中看到是把_site文件夹软链接到mirror文件夹下，但是我试了try_files的方法，访问网址如果不指定index.html文件名，则不会重定向到_sites下
我配置的这样：
try_files $uri $uri/ /_site/$uri;

**Comment by shankerwangmiao** [comment]
您好，您是指关于什么的配置？

**Comment by nightcoffee** [comment]
> 您好，您是指关于什么的配置？

手快按了回车，把问题编辑上了，谢谢

**Comment by shankerwangmiao** [comment]
我是指您所说的首页的配置是什么意思？我们首页没有特殊配置。

**Comment by nightcoffee** [comment]
> 我是指您所说的首页的配置是什么意思？我们首页没有特殊配置。

即如果把_site目录以软链接方式到mirror的网站目录下，那么网站的根目录下是否是存在一个_site目录软链接？
webroot
├─ _site -> /xxx/xxx/_site
├─ centos
└─ ubuntu
那当我访问网站根目录时是如何显示_site下的index.html的呢？
即既能通过
http://www.xxx.com/ubuntu 访问ubuntu镜像
也可以通过
http://www.xxx.com 访问到_site目录下的首页

还是我理解错误了……不是把_site目录软链接过去而是整个文件夹内容链接过去了？

**Comment by shankerwangmiao** [comment]
> 还是我理解错误了……不是把_site目录软链接过去而是整个文件夹内容链接过去了？

是的

**Comment by nightcoffee** [comment]
> > 还是我理解错误了……不是把_site目录软链接过去而是整个文件夹内容链接过去了？
> 
> 是的

感谢！
