### ISSUE TITLE
nginx的git库服务提供问题

### ISSUE THREAD

**Issue by nightcoffee** [tuna/mirror-web#302]
有两个问题
1. git形式的镜像库都以git路径为前缀，后端以git-http-backend提供服务，nginx上我通过下面这样的设置可以实现

```
location ~ /git(/.*) {
      fastcgi_pass unix:/var/run/fcgiwrap.socket;
      fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
      fastcgi_param GIT_HTTP_EXPORT_ALL "";
      fastcgi_param GIT_PROJECT_ROOT /var/tunasync/;
      fastcgi_param PATH_INFO $1;
      include /etc/nginx/fastcgi_params;
    }
```

但是有看到网上说应该区分静态文件直接nginx提供服务，这样性能可以更好，只有git相关文件才需要传递给git-http-backend。但是不知道如何区分呢？

2. git-repo这个库镜像站提供这样的下载初始化脚本是怎么实现的？这个路径并不是真实存在的（实际内容在/git/git-repo/git-repo）而且与仓库地址完全相同
`curl https://mirrors.bfsu.edu.cn/git/git-repo -o repo`
即使我手动改成curl https://xxxx.com/git/git-repo/git-repo -o repo似乎也获取不了/git/git-repo/git-repo这个文件
`
2022/01/14 07:42:34 [error] 1547952#1547952: *4 FastCGI sent in stderr: "Request not supported: '/var/tunasync/git-repo/git-repo'" while reading response header from upstream, client: x.x.x.x, server: _, request: "GET /git/git-repo/git-repo HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "xxxx.com"
`

不知以上两个问题能否直接提供一下nginx的配置参考呢？感谢

**Comment by shankerwangmiao** [comment]
> 有两个问题
> 
> 1. git形式的镜像库都以git路径为前缀，后端以git-http-backend提供服务，nginx上我通过下面这样的设置可以实现
> 
> ```
> location ~ /git(/.*) {
>       fastcgi_pass unix:/var/run/fcgiwrap.socket;
>       fastcgi_param SCRIPT_FILENAME /usr/lib/git-core/git-http-backend;
>       fastcgi_param GIT_HTTP_EXPORT_ALL "";
>       fastcgi_param GIT_PROJECT_ROOT /var/tunasync/;
>       fastcgi_param PATH_INFO $1;
>       include /etc/nginx/fastcgi_params;
>     }
> ```
> 
> 但是有看到网上说应该区分静态文件直接nginx提供服务，这样性能可以更好，只有git相关文件才需要传递给git-http-backend。但是不知道如何区分呢？

`/git` 目录下不存在需要服务的静态文件
 
> 
> 2. git-repo这个库镜像站提供这样的下载初始化脚本是怎么实现的？这个路径并不是真实存在的（实际内容在/git/git-repo/git-repo）而且与仓库地址完全相同
>    `curl https://mirrors.bfsu.edu.cn/git/git-repo -o repo`
>    即使我手动改成curl https://xxxx.com/git/git-repo/git-repo -o repo似乎也获取不了/git/git-repo/git-repo这个文件
>    `2022/01/14 07:42:34 [error] 1547952#1547952: *4 FastCGI sent in stderr: "Request not supported: '/var/tunasync/git-repo/git-repo'" while reading response header from upstream, client: x.x.x.x, server: _, request: "GET /git/git-repo/git-repo HTTP/1.1", upstream: "fastcgi://unix:/var/run/fcgiwrap.socket:", host: "xxxx.com"`
>

在配置中 Hack 了一下：

```
location = /git/git-repo {
        alias /path/to/git-repo/git-repo;
}
```
 
> 不知以上两个问题能否直接提供一下nginx的配置参考呢？感谢
