### ISSUE TITLE
Lua script for the reverse proxy to add additional header tags.

### ISSUE THREAD

**Issue by sickcodes** [tuna/mirror-web#306]
I love the project, but the results are appearing higher than the real aur.archlinux.org mirror, in the case of the AUR:

```
<link rel="canonical" href="https://aur.archlinux.org" />
<html lang="zh-CN">
<link rel="alternate" href="https://aur.tuna.tsinghua.edu.cn" hreflang="zh-CN" />
```

https://www.reddit.com/r/archlinux/comments/sksjok/mirror_aurtunatsinghuaeducn_is_appearing/

For example, assuming this is Tengine/Nginx/Openresty? :

```lua
body_filter_by_lua_block {
    replacestr = '<link rel="canonical" href="https://aur.archlinux.org" /><html lang="zh-CN"><link rel="alternate" href="https://aur.tuna.tsinghua.edu.cn" hreflang="zh-CN" /></head>'
    ngx.arg[1] = ngx.re.sub(ngx.arg[1],"</head>", replacestr)
    return
}
```

**Comment by phy25** [comment]
See also https://github.com/tuna/issues/issues/649 and https://github.com/tuna/issues/issues/1424.

**Comment by shankerwangmiao** [comment]
We are planning to stop this service according to https://github.com/tuna/issues/issues/1424 , and thus won't make any further changes.
