### ISSUE TITLE
镜像列表始终显示tuna

### ISSUE THREAD

**Issue by zedpass** [tuna/mirror-web#307]
您好，我已经在nginx中将/static/tunasync.json反代到了http://127.0.0.1:10086/jobs ，tunasync.json中的内容也是我同步的列表，但不知道为何在首页显示的镜像列表中会多出一个tuna，tunasync.json中是没有这个字段的，请问如何去除?

**Comment by phy25** [comment]
https://github.com/tuna/mirror-web/blob/7819a024972b3d40b28796bd84738f02de268251/_data/options.yml#L450

**Comment by zedpass** [comment]
十分感谢，将 unlisted_mirrors 下的 is_master 由 true 改为 false 后成功隐藏
