### ISSUE TITLE
Consider remove -proposed repos

### ISSUE THREAD

**Issue by KexyBiscuit** [tuna/mirror-web#32]
-proposed repos, as [Ubuntu Wiki](https://wiki.ubuntu.com/Testing/EnableProposed) shows, are pre-released repos, which are not ready for production.

So, should we remove it from the [help file](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/)?

**Comment by bigeagle** [comment]
I guess it's more appropriate to disable it by default. like
```
# uncomment this if you want to enable pre-release testing packages
# deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu/ xenial-proposed main multiverse restricted universe
```
