### ISSUE TITLE
The mirror-web cannot display the mirror page,It may be because of nginx configuration

### ISSUE THREAD

**Issue by leochen12-rgb** [tuna/mirror-web#345]
I am using nginx as the proxy server,It is configured which --add-dynamic-module=/opt/ngx-fancyindex-0.5.2 --add-dynamic-module=/opt/njs-0.7.0/nginx.
But now the homepage can be displayed normally, and the mirror files cannot be displayed.
Can I refer to how Tuna configures the proxy server?

fancyindex_header /fancy-index/before.html;
fancyindex_footer /fancy-index/after.html;

fancyindex_ignore "examplefile.html";
fancyindex_ignore "example";

**Comment by shankerwangmiao** [comment]
```

**Comment by shankerwangmiao** [comment]
```
fancyindex_header /fancy-index/before;
fancyindex_footer /fancy-index/after;
#fancyindex_show_path off;
fancyindex_exact_size off;
fancyindex_time_format "%d %b %Y %H:%M:%S +0000";
fancyindex_name_length 256;
js_path /etc/nginx/njs;
js_import fancyIndexRender from fancy_index.njs;

map $http_user_agent $isbrowser {
  default 0;
  "~*validation server" 0;
  "~*mozilla" 1;
}

location /fancy-index {
        internal;
        root /srv/mirrors;
        subrequest_output_buffer_size 100k;
        location = /fancy-index/before {
                js_content fancyIndexRender.fancyIndexBeforeRender;
        }
        location = /fancy-index/after {
                js_content fancyIndexRender.fancyIndexAfterRender;
        }
}
location{
        //.......
         fancyindex on;
}
```

**Comment by leochen12-rgb** [comment]
Thank you for your reply, and I solved this problem by referring to the previous issue

https://github.com/tuna/mirror-web/issues/233
https://github.com/tuna/mirror-web/issues/276
