### ISSUE TITLE
mirror-web怎样和tunasync后端对接?

### ISSUE THREAD

**Issue by wxf26054** [tuna/mirror-web#366]
web搭建完成, 但是没有任何更新, 状态页面图片无法加载.

**Comment by ZenithalHourlyRate** [comment]
您可以参考 https://github.com/tuna/mirror-web/issues/233#issuecomment-746378214

**Comment by wxf26054** [comment]
static/status/disk.json 这个要怎样生成
提到的系统状态图表, 这个要怎样渲染呢?

**Comment by shankerwangmiao** [comment]
> static/status/disk.json 这个要怎样生成
> 
> 提到的系统状态图表, 这个要怎样渲染呢?

请参考 https://github.com/tuna/mirror-web/issues/233#issuecomment-950463372

**Comment by wxf26054** [comment]
多谢
