### ISSUE TITLE
cdn.jsdelivr.net无法访问

### ISSUE THREAD

**Issue by SRY-CTB** [tuna/mirror-web#381]
最近cdn.jsdelivr.net无法访问，能否更换其他的下载源呢

**Comment by liudonghua123** [comment]
试试 https://gitee.com/eebbk/Chinajsdelivr#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95 这个呢？搭配 https://github.com/hans000/easy-interceptor
添加规则

```json
{
    "test": "cdn.jsdelivr.net",
    "groupId": "default",
    "response": {
        "code": 0,
        "data": [],
        "message": "success"
    }
}
```

```js
onRedirect((rule) => {
    const redirectUrl = new URL(rule.url);
    redirectUrl.host = 'jsd.cdn.zzko.cn';
    return redirectUrl.toString();
})
```

这个能解决部分问题，一些新的库可能还没同步，例如访问 https://pyodide.org/en/stable/console.html 其中的 jquery https://cdn.jsdelivr.net/npm/jquery (https://jsd.cdn.zzko.cn/npm/jquery) 没有问题，但是 pyodide https://cdn.jsdelivr.net/pyodide/v0.26.0/full/pyodide.mjs （https://jsd.cdn.zzko.cn/pyodide/v0.26.0/full/pyodide.mjs) 就不行了

![image](https://github.com/tuna/mirror-web/assets/2276718/5ca2cf00-87e0-4aaa-bf3d-22da25b4b24a)
