### ISSUE TITLE
Add RSS support for news.

### ISSUE THREAD

**Issue by fernvenue** [tuna/mirror-web#387]
The TUNA mirror site publishes important announcements related to site maintenance, mirror site updates, and software package removals through news. This is an important information channel for mirror site users, especially for downstream server maintenance developers. However, accessing this information through the front-end interface can be cumbersome. Writing scripts to continuously fetch page information might be one solution, but it can cause access pressure on the site and be considered as abuse or frequent access.

Therefore, I think it would be great if the news section could support RSS. This would provide users with a convenient method to receive information by directly using their local RSS applications. Additionally, adhering to RSS update frequency norms would protect the site from excessive access.

By the way, if RSS support for accessing news information is already available, please kindly let me know :)

**Comment by kLiHz** [comment]
Have you tried <https://mirrors.tuna.tsinghua.edu.cn/feed.xml> yet? 😆

**Comment by fernvenue** [comment]
> Have you tried https://mirrors.tuna.tsinghua.edu.cn/feed.xml yet? laughing

Yea, seems https://mirrors.tuna.tsinghua.edu.cn/feed.xml is actually doing this, but the RSS button is pointed to https://tuna.moe/feed.xml, I don't think it's good practice, but currently `/feed.xml` does the trick, so I'm gonna close this issue for now.
