### ISSUE TITLE
disk.json与isoinfo.json的数据不传入

### ISSUE THREAD

**Issue by ck1650817410** [tuna/mirror-web#398]
你好，又出现问题了，之前传入过一次disk.json的数据，这次不知道为啥网页不会更新了。数据是有的，就是网页不同步
![image](https://github.com/tuna/mirror-web/assets/125936974/aaabc6f3-ac2b-4e6a-b358-7444bcc6da0f)
![image](https://github.com/tuna/mirror-web/assets/125936974/66df2d12-1431-4627-a0a6-b82381d52d11)
![image](https://github.com/tuna/mirror-web/assets/125936974/c99d5719-90ee-4e1d-acac-1896bebe4125)

**Comment by shankerwangmiao** [comment]
请确认服务器上的 `/status/disk.json` 文件和预期情况相符。您可以通过在上述页面上打开浏览器的开发者工具，查看实际获取到的 disk.json 文件。

**Comment by ck1650817410** [comment]
并不相符
![image](https://github.com/tuna/mirror-web/assets/125936974/f0fed7b7-6793-4816-8950-062a0eb6f45d)
![image](https://github.com/tuna/mirror-web/assets/125936974/5d221bb2-5d82-4292-a664-3a3b50c88f86)

**Comment by Harry-Chen** [comment]
此文件不是 tunasync 或 mirror-web 负责维护，请您自行使用脚本等手段维护相关信息。

**Comment by ck1650817410** [comment]
但服务器中获取的数据是没问题的，这是网页获取服务器上数据时出现问题吧

**Comment by Harry-Chen** [comment]
mirror-web 不使用什么特殊技术下载内容，您使用浏览器或者 curl 访问到的内容是一样的，此问题和 mirror-web 没有关系。
因此，请您检查您的 nginx 配置，以及此文件生成的相应过程。

**Comment by shankerwangmiao** [comment]
从您提供的截图来看，浏览器获取到的 disk.json 文件的内容，与界面上显示的磁盘占用状态一致，因此本项目不存在显示出错的问题。建议您自行排查 disk.json 文件的内容与预期不符的原因。您可以从以下几个方面入手：

- 在服务器上查看该文件的内容，观察其是否与预期相符；
- 检查生成/更新 disk.json 的脚本是否正常执行；
- 检查您的 HTTP 服务器软件是否错误设置了缓存标头，致使浏览器从缓存中调取了旧的数据。
