### ISSUE TITLE
关于子目录样式调用问题

### ISSUE THREAD

**Issue by CHEN-Technology** [tuna/mirror-web#405]
抱歉又来麻烦你们了，我今天进入网站发现子目录未正确调用样式，浏览器也未报错，但我确定之前是没问题的，我试过用默认的静态文件配置进行也依旧未正确调用
![image](https://github.com/tuna/mirror-web/assets/125936974/e16eaa45-0414-40a0-9c0a-0fac4cc9e4e8)
![image](https://github.com/tuna/mirror-web/assets/125936974/23f101ab-111e-4345-8f79-32caefe43228)

**Comment by shankerwangmiao** [comment]
请检查配置文件中，`$isbrowser` 是否正确定义，正确的定义是：

```
map $http_user_agent $isbrowser {
  default 0;
  "~*validation server" 0;
  "~*mozilla" 1;
}
```

**Comment by CHEN-Technology** [comment]
是的，我缺少了它，感谢
