### ISSUE TITLE
建议提供适用于Docker-Compose配置文件

### ISSUE THREAD

**Issue by sakuracat1** [tuna/mirror-web#409]
新版本README文件删去了本地安装ruby等相关组件的内容转而使用Docker部署，建议提供适用于docker-compose的配置文件，以降低使用门槛，提高效率

**Comment by shankerwangmiao** [comment]
您好，此处 docker 并非用于提供服务的，而是给前端页面生成的过程提供运行环境。具体运用的时候，启动 docker 镜像内的 jekyll 渲染程序，将本源代码渲染成 html 页面。渲染完毕后 jekyll 和 docker 容器的生命周期即宣告终止，并不长时间运行提供服务。对外提供前端页面的服务，是由静态 http 文件服务器完成的，与本项目和 docker 镜像不相关。


基于上述理由，没有必要使用 docker-compose 完成上述任务。
