### ISSUE TITLE
ubuntu help 页面应当更新 Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by ZtRXR** [tuna/mirror-web#421]
ubuntu help 页面应当更新 Ubuntu 24.04 LTS

**Comment by ZtRXR** [comment]
https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/

**Comment by Harry-Chen** [comment]
Will be handled in https://github.com/mirrorz-org/mirrorz-help/pull/140
