### ISSUE TITLE
建议添加geninfo/genisolist.ini配置文件编辑指引

### ISSUE THREAD

**Issue by stackinspector** [tuna/mirror-web#425]
注意到每当一个新的软件类镜像请求被批准后，维护者都会提醒申请者可以编辑此repo下的geninfo/genisolist.ini配置文件，以在首页上添加下载直链。但我似乎没有找到与之相关的文档或者编辑指引，python脚本有一定复杂性且涉及到rsync等与添加配置关系不大的细节，自行分析可能出现理解偏差，而且也没有有关如何调试的详细说明（不知道运行所需的环境等先决条件，不敢直接运行）。故希望添加编辑指引以方便贡献者。
编辑指引中可能需要说明：遇到类似OBS的多版本情况如何处理（guideline level）；正则匹配的输入是全路径还是哪一部分还是文件名；正则不匹配的文件是否会被过滤掉；匹配组是否具有语义，还是只使用捕获组；`platform` `type` `version`的含义及输出方式。
另外NanaZip的配置需要同时包含并区分Release和Pre-Release（目前只包含最新的Pre-Release）以及msixbundle和Windows10 PreinstallKit（目前只显示版本）；CrystalDiskInfo和CrystalDiskMark两个软件在目前的配置文件中存在，但是在镜像站线上并不显示，是否是配置存在错误。如果能提供编辑指引，我将乐意贡献。

**Comment by taoky** [comment]
我计划近期在 MirrorZ 项目中添加 genisolist 的文档与参考实现。

**Comment by stackinspector** [comment]
似乎现在tuna镜像站的/static/status/isoinfo.json直接返回空列表了？bfsu的还有

**Comment by shankerwangmiao** [comment]
> 似乎现在tuna镜像站的/static/status/isoinfo.json直接返回空列表了？bfsu的还有

是的，因为 #422 引入的修改导致执行失败，已经在 3926cd52 中修复。

**Comment by stackinspector** [comment]
抱歉没有注意到文件开头的注释文档……那天晚上正则写的我有点迷糊就跑来提了个issue……不过未来能有更完善的文档当然是好事。
CrystalDiskInfo和CrystalDiskMark的问题看到已经修复了。在 #428 中添加了之前我在 tuna/issues#1944 中提议增加的Deno，修复了前面提到的NanaZip的问题，顺手让rust-analyzer显示了版本。

**Comment by Harry-Chen** [comment]
请参见 https://github.com/mirrorz-org/genisolist 项目，TUNA 将迁移到该项目。
