### ISSUE TITLE
Invalid integrity for bs3-polyfill.scss

### ISSUE THREAD

**Issue by Crystal-RainSlide** [tuna/mirror-web#433]
Log:

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://mirrors.tuna.tsinghua.edu.cn/assets/bs3-polyfill-D-SBFs68.css' with computed SHA-256 integrity 'P9Uwo4Jep5O8z4BWrm2n6HUmxksUVQ8dRLMNI7jK63k='. The resource has been blocked.`

Code:

https://github.com/tuna/mirror-web/blob/ea51e0175199bab1fa12ceb106fdd41cc333e797/_includes/head.html#L34

Either calculate or remove that integrity will fix this problem.

**Comment by shankerwangmiao** [comment]
See #420
