### ISSUE TITLE
请求增加IPV6 环境支持

### ISSUE THREAD

**Issue by DIYer22** [tuna/mirror-web#44]
首先 学习TUNA的无私奉献 
希望你们能支持IPV6 
那么更新下载速度会对大家有质的提升吧

**Comment by bigeagle** [comment]
我们一直都资瓷 IPv6 啊！

**Comment by DIYer22** [comment]
是这样的 我把ipv4协议关闭了 用你们的ipv6 地址 `[2402:f000:1:416:166:111:206:63]` 
只能访问主页 并被重新定向到你们的域名 
无法直接访问ipv6 例如
`https://[2402:f000:1:416:166:111:206:63]/anaconda/archive/`
（其他ipv6网站均可纯IPv6协议访问）

**Comment by bigeagle** [comment]
哦，这个原因有很多，首先 nginx 上有多个网站，必须使用域名区分；其次 HTTPS 证书也会校验域名。
mirrors.tuna.tsinghua.edu.cn 是有 AAAA 记录的，只要你那边支持 IPv6 的话就会优先走 IPv6
或者你可以使用 mirrors6.tuna.tsinghua.edu.cn 强制走 v6

**Comment by DIYer22** [comment]
完美解决 谢谢啦
