### ISSUE TITLE
给nginx的默认index页面做点美化

### ISSUE THREAD

**Issue by scateu** [tuna/mirror-web#45]
虽然不知道有没有必要...

我看OpenWrt的Index就改了一点点, 感觉上就很漂亮了, 心情大好:

 -  <https://downloads.openwrt.org/chaos_calmer/15.05.1/>

**Comment by huiyiqun** [comment]
这是nginx…没看出来…

**Comment by scateu** [comment]
不是nginx就是apache...



啊果然是nginx:  https://downloads.openwrt.org/chaos_calmer/15.05.1/adfasasdfasdf


主要是我几年前看这个的时候,界面还是很朴素的白花花的那种...



一转眼就这么肤(piao)浅(liang)了

**Comment by huiyiqun** [comment]
好像得用非官方的fancyindex?

我觉得不如用autoindex _format输出json 然后用vuejs简单画一个?

**Comment by scateu** [comment]
<link rel="stylesheet" href="
https://openwrt.org/.styles/dir-listing.css" type="text/css"/>


不知道在哪里注入

**Comment by scateu** [comment]
https://www.linickx.com/css-styling-nginx-directory-listings



这个上面说



``` location /files { add_before_body /files/nginx-before.txt;
add_after_body /files/nginx-after.txt; autoindex on; }
```

这样就行

**Comment by dotkrnl** [comment]
提供前端的按类型检索功能等

**Comment by scateu** [comment]
刚发现miao wang已经给搞好了，棒！
