### ISSUE TITLE
[Anaconda/Important enhancement] 请注明Anaconda的Python版本

### ISSUE THREAD

**Issue by CDLuminate** [tuna/mirror-web#51]
Reproduce:
```
1. https://mirrors.tuna.tsinghua.edu.cn
2. 获取下载链接
3. 应用软件
4. Anaconda
5. 给出的下载链接并没有标注出明确的Python版本
```

比如我就是没注意这个问题，想要Py3版本的Anaconda然后迷迷糊糊下载了Anaconda2。

请在给出的链接中注明这是`Anaconda2`还是`Anaconda3`，Thanks.

**Comment by xavieryao** [comment]
Fixed in a1e704c160e0 , but not deployed yet.

**Comment by huiyiqun** [comment]
Fixed in https://github.com/tuna/mirror-web/commit/8c3643d8c8a5cfa173cd3d455eda0f36dae3aa8d.
