### ISSUE TITLE
镜像站主页上过滤检索

### ISSUE THREAD

**Issue by dotkrnl** [tuna/mirror-web#53]
USTC Mirrors 的页面可以通过过滤，用户反馈这一功能可能会使得使用更加便捷。
March 27, 2017 6:44 PM

**Comment by Harry-Chen** [comment]
@huiyiqun 惠老师有空加一个？

**Comment by huiyiqun** [comment]
我做不出来更漂亮的，杰哥的代码也没啥问题。

**Comment by z4yx** [comment]
所以这个issue算解决了吧
