### ISSUE TITLE
anaconda添加了清华大学的镜像源，但安装时经常显示网络错误

### ISSUE THREAD

**Issue by gehongyi** [tuna/mirror-web#59]
我每次安装都会出现类似下面的代码，显示CondaHTTPError，每次要尝试好几十遍，好花好久的时间才能安装好第三方库。。。能帮我找找原因么？我记得以前安装时很快的。谢谢了

C:\Users\Administrator>conda install -c conda-forge basemap-data-hires
Fetching package metadata ..........

CondaHTTPError: HTTP None None
for url <None>

An HTTP error occurred when trying to retrieve this URL.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='repo.continuum.io', port
=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Cause
d by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConn
ection object at 0x00000000051A5C88>, 'Connection to repo.continuum.io timed out
. (connect timeout=6.1)'))",),)

**Comment by bigeagle** [comment]
这是连接官方源失败，可以考虑把官方源干掉

**Comment by gehongyi** [comment]
@bigeagle ,请问如何删除官方源？谢谢

**Comment by xavieryao** [comment]
@gehongyi https://stackoverflow.com/questions/39558316/how-can-i-remove-a-url-channel-from-anaconda

**Comment by gehongyi** [comment]
@xavieryao 非常感谢哈
