### ISSUE TITLE
page scroll to top when modal(help dialog) appears

### ISSUE THREAD

**Issue by huiyiqun** [tuna/mirror-web#6]
I used to consider this as a feature of modal of bootstrap, but it is not.

Compare with [this demo](http://getbootstrap.com/javascript/#live-demo).

Even though I implemented it, I have no idea with it.

**Comment by bigeagle** [comment]
It's because of the `href="#"`

**Comment by huiyiqun** [comment]
I'm trying fix it.

**Comment by bigeagle** [comment]
Great job!
