### ISSUE TITLE
如何生成json的动态数据

### ISSUE THREAD

**Issue by liukuan1** [tuna/mirror-web#65]
这些数据是怎么动态获取的
wget https://mirrors.tuna.tsinghua.edu.cn/static/tunasync.json -O static/tunasync.json
wget https://mirrors.tuna.tsinghua.edu.cn/static/tunet.json -O static/tunet.json
wget https://mirrors.tuna.tsinghua.edu.cn/static/isoinfo.json -O static/isoinfo.json

**Comment by alick** [comment]
我猜是服务器端一些脚本生成的。

**Comment by shankerwangmiao** [comment]
这几个文件的情况各不相同，isoinfo.json 是有脚本在定时生成，脚本在 https://github.com/tuna/mirror-web/blob/master/geninfo/genisolist.py

tunasync.json 由 nginx 反代给 tunasync 的 manager，由 manager 产生输出，相关代码在 https://github.com/tuna/tunasync/blob/master/manager/status.go

tunet.json 直接由 nginx 产生，本意是用于判断用户是否在校园网内，却访问了镜像站校园网外的 IP 地址；如果是，则在前端产生提醒，提醒用户防止产生过多流量。目前该功能已经废除，因为镜像站已经没有校园网外的地址了。相关代码如下：

```
geo $ipwhitelist {
        default 1;
        127.0.0.0/8 0;
        172.18.0.0/16 0;
        166.111.0.0/16 0;
        59.66.0.0/16 0;
        101.5.0.0/16 0;
        101.6.0.0/16 0;
        183.172.0.0/16 0;
        183.173.0.0/16 0;
        118.20.0.0/20 0;
        :: 0;
}

map $ipwhitelist $limit {
        1 $binary_remote_addr;
        0 "";
}

limit_conn_zone $limit zone=limit:10m;

location = /static/tunet.json {
        return 200 "false";
        # F**k nginx does not support nested if nor "and" "or" "else" "not"
        # Halt! Magic here! Don't Touch!
        
        # set $outer "0";
        # if ($limit) {
        #       set $outer 1;
        # }
        # set $insider_out "0";
        # if ($server_addr = "202.112.3.6") {
        #       set $insider_out "1+${outer}";
        # }
        # if ($insider_out = "1+0") {
        #       return 200 "true";
        # }
        # return 200 "false";
}
```

**Comment by bubbleatgit** [comment]
貌似现在已失效？

**Comment by bubbleatgit** [comment]
tunasync.json 其实是tunasync管理器的manager提供的一个接口，接口地址为 http://`manager:listenport`>/jobs。

接口作用及接口名称查看 https://github.com/tuna/tunasync/blob/master/manager/server.go 。

生成tunasync.json的代码，查看 https://github.com/tuna/tunasync/blob/master/internal/status_web.go
