### ISSUE TITLE
请取消华文黑体的使用

### ISSUE THREAD

**Issue by wsxyeah** [tuna/mirror-web#71]
目前 macOS 跟 iOS 的系统字体已经换成了苹方。

毫无疑问，华文黑体已经过时了。希望可以去掉 `font-family` 中的 `Heiti SC`。

**Comment by shankerwangmiao** [comment]
貌似在 https://github.com/tuna/mirror-web/blob/178f579e497d9e44257d9e6a5c94d6fb42002e2f/static/css/style.scss#L26 

求 pr

**Comment by wsxyeah** [comment]
@shankerwangmiao see #72

**Comment by shankerwangmiao** [comment]
Merged, thanks
