### ISSUE TITLE
lineageOS 帮助将 github 的 remote 直接指向了 tuna 

### ISSUE THREAD

**Issue by shankerwangmiao** [tuna/mirror-web#82]
如题，这样修改之后，如果用户自行添加 github 上引用的其他的仓库会出现问题。 如 https://github.com/tuna/issues/issues/333

建议新加一个 remote，把 default remote 从 github 指向新的 remote

**Comment by huiyiqun** [comment]
See #90

**Comment by Harry-Chen** [comment]
Solved by #90
