### ISSUE TITLE
emmm.....装不上了 in Debian

### ISSUE THREAD

**Issue by NciYuan-Net** [tuna/mirror-web#86]
拉Master分支，Debian系统的，按照md的教程里，到Jekyll install那一步的时候
先
``
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (< 2, >= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
/usr/lib/ruby/vendor_ruby/bundler/runtime.rb:34:in `block in setup': You have already activated jekyll-watch 2.0.0, but your Gemfile requires jekyll-watch 1.5.1. Prepending `bundle exec` to your command may solve this. (Gem::LoadError)
        from /usr/lib/ruby/vendor_ruby/bundler/runtime.rb:19:in `setup'
        from /usr/lib/ruby/vendor_ruby/bundler.rb:121:in `setup'
        from /var/lib/gems/2.1.0/gems/jekyll-3.7.2/lib/jekyll/plugin_manager.rb:50:in `require_from_bundler'
        from /var/lib/gems/2.1.0/gems/jekyll-3.7.2/exe/jekyll:11:in `<top (required)>'
        from /usr/local/bin/jekyll:23:in `load'
        from /usr/local/bin/jekyll:23:in `<main>'
``
我理解大概意思应该是Jekyll-watch的版本过高的了，然后先uninstall了，然后又-v 1.5.1安装了一下
接着又出现
``
/usr/local/lib/site_ruby/2.1.0/rubygems/dependency.rb:315:in `to_specs': Could not find 'jekyll-watch' (~> 2.0) - did find: [jekyll-watch-1.5.1,jekyll-watch-1.0.0] (Gem::LoadError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.1.0:/var/lib/gems/2.1.0:/usr/share/rubygems-integration/2.1.0:/usr/share/rubygems-integration/2.1:/usr/share/rubygems-integration/all', execute `gem env` for more information
        from /usr/local/lib/site_ruby/2.1.0/rubygems/specification.rb:1311:in `block in activate_dependencies'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/specification.rb:1300:in `each'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/specification.rb:1300:in `activate_dependencies'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/specification.rb:1282:in `activate'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:67:in `block in gem'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:66:in `synchronize'
        from /usr/local/lib/site_ruby/2.1.0/rubygems/core_ext/kernel_gem.rb:66:in `gem'
        from /usr/local/bin/jekyll:22:in `<main>'
``
小白求解
这些大佬们了
以前没用过Ruby

**Comment by shankerwangmiao** [comment]
建议使用 `bundle install --path vendor/bundle` 命令

然后后面的诸如 `jekyll build` 和 `jekyll serve` 命令都替换成 `bundle exec jekyll build` 和 `bundle exec jekyll serve`
