### ISSUE TITLE
git-repo帮助修改

### ISSUE THREAD

**Issue by huanghe2015** [tuna/mirror-web#87]
原链接：https://mirrors.tuna.tsinghua.edu.cn/help/git-repo/
原来一直用修改 ~/.bashrc的方法，发现并没有什么用，直到我碰到了这篇：http://blog.csdn.net/hm11104105/article/details/75617615
希望能以此为参考，尽快修改。

**Comment by shankerwangmiao** [comment]
并不是这样，从 repo 命令开头的语句很明显看出来

``` "python"

REPO_URL = os.environ.get('REPO_URL', None)
if not REPO_URL:
  REPO_URL = 'https://gerrit.googlesource.com/git-repo'

```

直接在环境变量中指定 `REPO_URL` 是有效的。同时，不建议直接修改 `repo` 脚本的内容。如果您遇到了修改 `bashrc` 无效的问题，请检查：1. 修改之后是否重启了中断模拟器；2. 你的 shell 是否是 bash，如果不是，请修改你所使用的 shell 程序对应的 rc 文件。

**Comment by huanghe2015** [comment]
原来shell解释器不止bash。。。

**Comment by huanghe2015** [comment]
抱歉，我在repo里面没有找到这句，请问是因为版本（https://packages.ubuntu.com/artful/repo）原因吗？

**Comment by gaoyichuan** [comment]
你提供的包内 repo 命令中是包含这些代码的，再看看？
