### ISSUE TITLE
issue 页面不能在线回复，只能通过邮件

### ISSUE THREAD

**Issue by haobug** [tuna/mirror-web#9]
@huiyiqun 没有看见你说的 justin

**Comment by bigeagle** [comment]
你好，issues请见 https://github.com/tuna/django-helpdesk

**Comment by haobug** [comment]
@bigeagle 意思是上游已知问题 ？ django-helpdesk 的 issue 是空了居然。

**Comment by bigeagle** [comment]
的确是上游问题，我们fork了，请到那里提issue

**Comment by bigeagle** [comment]
我们fork了，的确是上游问题，请到 https://github.com/tuna/django-helpdesk/issues 提issue

**Comment by haobug** [comment]
你们的后台账号管理等权限，你们整理一下提到上游吧。我就不瞎搅合了 @bigeagle

**Comment by bigeagle** [comment]
哈哈，thanks all the same！

On Mon, Mar 23, 2015 at 1:06 PM, qinghao <notifications@github.com> wrote:

> 你们的后台账号管理等权限，你们整理一下提到上游吧。我就不瞎搅合了 @bigeagle <https://github.com/bigeagle>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tuna/mirror-web/issues/9#issuecomment-84812242>.
>



-- 
Open Source, Open Mind
