### ISSUE TITLE
MikTeX 镜像

### ISSUE THREAD

**Issue by Stone-Zeng** [tuna/mirror-web#95]
现在的 CTAN 镜像似乎不支持 MikTeX，在官网 <https://miktex.org/pkg/repositories> 并不能看到有中国的镜像站，于是每次就被跳转到台湾，然后又访问不了。

但该有的文件 tuna 上其实都有，只是不知道为什么不能拿来用（设置 `mpm --repository=https://mirrors.tuna.tsinghua.edu.cn/CTAN/systems/win32/miktex/tm/packages/` 会报错）。是不是应该问下 MikTeX 他们那边？

**Comment by Harry-Chen** [comment]
mirrors 服务相关问题请到 https://github.com/tuna/issues/ 的 issue 提出

MikTeX 这个问题由来已久，以前它们还把 TUNA 当作某个非洲国家的镜像站。目前查看是正常的。
